steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['pubsub', 'topics', 'publish', 'projects/playwright-sandbox-403213/topics/playwright-run-status', '--message', 'running']

- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/rapattonimusic/playwright-sandbox']

- name: 'node'
  entrypoint: 'npm'
  args: ['install']
  dir: 'playwright-sandbox'

# # Step: Publish the message to the Pub/Sub topic
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   args:
#   - 'gcloud'
#   - 'pubsub'
#   - 'topics'
#   - 'publish'
#   - 'projects/playwright-sandbox-403213/topics/playwright-run-status'
#   - '--message={"repo": "o-accounts", "status": "pass"}'

# Publish to Pub/Sub to trigger Playwright tests
# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['pubsub', 'topics', 'publish', 'projects/playwright-sandbox-403213/topics/playwright-run-status', '--message', '{"repo": "o-accounts", "status": "pass"}']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['pubsub', 'topics', 'publish', 'projects/playwright-sandbox-403213/topics/playwright-run-status', '--message', '{"repo": "oAccounts", "status": "fail"}']
