steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['pubsub', 'topics', 'publish', 'playwright-run-status-sub', '--message', 'running']

- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/rapattonimusic/playwright-sandbox']

- name: 'node'
  entrypoint: 'npm'
  args: ['install']
  dir: 'playwright-sandbox'

- name: 'node'
  entrypoint: 'npx'
  args: ['playwright', 'install']
  dir: 'playwright-sandbox'

- name: 'node'
  entrypoint: 'npx'
  args: ['playwright', 'test']
  dir: 'playwright-sandbox'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['pubsub', 'topics', 'publish', 'playwright-run-status-sub', '--message', 'complete']