steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['pubsub', 'topics', 'publish', 'projects/playwright-sandbox-403213/topics/playwright-run-status', '--message', 'running']

- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/rapattonimusic/playwright-sandbox']

- name: 'node'
  entrypoint: 'npm'
  args: ['install']
  dir: 'playwright-sandbox'

- name: 'gcr.io/cloud-builders/gcloud'
  args: 
    - 'pubsub'
    - 'topics'
    - 'publish'
    - 'projects/playwright-sandbox-403213/topics/playwright-run-status'
    - '--message'
    - '{"statusMessage": "complete"}'