steps:
  # Docker Build (for Playwright tests)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    env:
      - 'BUILD_ID=$BUILD_ID'
    args: ['-c', 
      'docker build --no-cache --file Dockerfile.test -t playwright-sandbox:latest
      --build-arg RUN_PLAYWRIGHT_COMMAND="npm run test:e2e" ./']
  
  # Run Playwright Tests
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c',
      'docker run --rm -v $(pwd)/playwright-report:/app/playwright-report playwright-sandbox:latest']
    allow_failure: true

  # Store Playwright report to storage bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', 'playwright-report/*', 'gs://playwright-reports-hosted/BUILD_$BUILD_ID/']

  # Link to the report
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Playwright report is available at: https://storage.googleapis.com/playwright-reports-hosted/BUILD_$BUILD_ID/index.html"


artifacts:
  objects:
    location: 'gs://playwright-reports-hosted/BUILD_$BUILD_ID/'
    paths: ['playwright-report/**']
