steps:
  # Docker Build (for Playwright tests)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    env:
      - 'BUILD_ID=$BUILD_ID'
    args: ['-c', 
      'docker build --no-cache --file Dockerfile.test -t us-west2-docker.pkg.dev/$PROJECT_ID/playwright-artifacts/playwright:latest
      --build-arg CI_PROVIDER="gcloud"
      --build-arg GCLOUD_BUILD_ID=$BUILD_ID
      --build-arg TEST_ENVIRONMENT_NAME="staging"
      --build-arg RUN_PLAYWRIGHT_COMMAND="npm run test"
      --build-arg SLACK_REPORTING=false .']
  
  # Push
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-west2-docker.pkg.dev/$PROJECT_ID/playwright-artifacts/playwright:latest',
      ]

  # Run Playwright Tests
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c',
      'docker run --rm -v $(pwd)/playwright-report:/app/playwright-report us-west2-docker.pkg.dev/$PROJECT_ID/playwright-artifacts/playwright:latest']

images:
- 'us-west2-docker.pkg.dev/$PROJECT_ID/playwright-artifacts/playwright:latest'

artifacts:
  objects:
    location: 'gs://playwright-artifacts/'
    paths: ['playwright-report/**']
