steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gcloud', 'pubsub', 'topics', 'publish', 'projects/playwright-sandbox-403213/topics/playwright-run-status', '--message', '{"repo": "oAccounts", "status": "running"}']

- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/rapattonimusic/playwright-sandbox']

# Step: Run tests
- name: 'ubuntu'
  entrypoint: 'bash'
  args: ['-c', 'npm install && npm test; echo $? > exit_code.txt']

# Step: Publish the message to the Pub/Sub topic
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    TEST_OUTCOME=$(if [ $(cat exit_code.txt) -eq 0 ]; then echo "pass"; else echo "fail"; fi)
    gcloud pubsub topics publish projects/playwright-sandbox-403213/topics/playwright-run-status --message '{"repo": "oAccounts", "status": "'"$_TEST_OUTCOME"'"}'

substitutions:
  _TEST_OUTCOME: ''
