steps:
  # Step: Publish result to the Pub/Sub topic
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'pubsub'
      - 'topics'
      - 'publish'
      - 'projects/playwright-sandbox-403213/topics/playwright-run-status'
      - '--message'
      - '{"repo": "oSubscriptions", "environment": "production", "buildId": "$BUILD_ID", "projectId": "$PROJECT_ID"}'

  # Docker Build (for Playwright tests)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    env:
      - 'BUILD_ID=$BUILD_ID'
    args: ['-c', 
      'docker build --no-cache --file Dockerfile.test -t playwright-test-image:latest
      --build-arg CI_PROVIDER="gcloud"
      --build-arg GCLOUD_BUILD_ID=$BUILD_ID
      --build-arg TEST_ENVIRONMENT_NAME="production"
      --build-arg RUN_PLAYWRIGHT_COMMAND="npm run test"
      --build-arg SLACK_REPORTING=false .']
  
  # Run Playwright Tests
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c',
      # 'docker run --rm -v $(pwd)/playwright-report:/app/playwright-report playwright-test-image:latest']
      'docker run -v $(pwd)/playwright-report:/app/playwright-report playwright-test-image:latest; echo $? > /workspace/test_exit_code || true']

  # Publish to Pub/Sub topic to update Automation Dashboard
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Publish to Pub/Sub topic to update Automation Dashboard'
    entrypoint: 'bash'
    args: ['-c',
      'gcloud pubsub topics publish projects/playwright-sandbox-403213/topics/playwright-run-status --message "{\"repo\": \"oSubscriptions\", \"environment\": \"production\", \"buildId\": \"$BUILD_ID\", \"projectId\": \"$PROJECT_ID\"}"; test_exit_code=$(cat /workspace/test_exit_code); exit $test_exit_code']

