steps:
  # Step: Publish result to the Pub/Sub topic
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'pubsub'
      - 'topics'
      - 'publish'
      - 'projects/playwright-sandbox-403213/topics/playwright-run-status'
      - '--message'
      - '{"repo": "oAccounts", "buildId": "$BUILD_ID", "projectId": "$PROJECT_ID"}'
  
  # Checkout repo
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/rapattonimusic/playwright-sandbox']

  # Step: Install dependencies
  - name: 'mcr.microsoft.com/playwright:v1.43.1-jammy'
    entrypoint: 'npm'
    args: ['install']

  # Step: Run Playwright tests
  - name: 'mcr.microsoft.com/playwright:v1.43.1-jammy'
    entrypoint: 'bash'
    args: ['-c', 'npm run test; echo $? > /workspace/test_exit_code || true']

  # # Step: Install dependencies
  # - name: 'gcr.io/cloud-builders/npm'
  #   args: ['install']

  # # Step: Install Playwright dependencies
  # - name: 'node'
  #   entrypoint: 'npx'
  #   args: ['playwright', 'install-deps']

  # # Step: Install Playwright browsers
  # - name: 'node'
  #   entrypoint: 'npx'
  #   args: ['playwright', 'install']
  
  # # Step: Run Playwright tests
  # - name: 'node'
  #   entrypoint: 'npx'
  #   args: ['-c',
  #     'playwright test; echo $? > /workspace/test_exit_code || true ' ]
  
  # # Step: Run tests
  # - name: 'ubuntu'
  #   entrypoint: 'bash'
  #   args: ['-c', 'sleep 120']

  # Step: Publish result to the Pub/Sub topic
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c',
      'gcloud pubsub topics publish projects/playwright-sandbox-403213/topics/playwright-run-status --message "{\"repo\": \"oAccounts\", \"buildId\": \"$BUILD_ID\", \"projectId\": \"$PROJECT_ID\"}"; test_exit_code=$(cat /workspace/test_exit_code); exit $test_exit_code']

  # # Step: Publish result to the Pub/Sub topic
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   args:
  #     - 'gcloud'
  #     - 'pubsub'
  #     - 'topics'
  #     - 'publish'
  #     - 'projects/playwright-sandbox-403213/topics/playwright-run-status'
  #     - '--message'
  #     - '{"repo": "oAccounts", "buildId": "$BUILD_ID", "projectId": "$PROJECT_ID"}'
  #     - 'test_exit_code=$(cat /workspace/test_exit_code); exit $test_exit_code'

