steps:
# Step: Publish to the Pub/Sub topic the job has started
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'pubsub'
      - 'topics'
      - 'publish'
      - 'projects/playwright-sandbox-403213/topics/playwright-run-status'
      - '--message'
      - '{"repo": "oAccounts", "buildId": "$BUILD_ID", "projectId": "$PROJECT_ID"}'

  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/rapattonimusic/playwright-sandbox']

  # Step: Run tests
  - name: 'ubuntu'
    entrypoint: 'bash'
    args: ['-c', 'echo "Run tests"']

  # Step: Publish result to the Pub/Sub topic
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'pubsub'
      - 'topics'
      - 'publish'
      - 'projects/playwright-sandbox-403213/topics/playwright-run-status'
      - '--message'
      - '{"repo": "oAccounts", "buildId": "$BUILD_ID", "projectId": "$PROJECT_ID"}'

